added audiofile folder and audio
BloomTech-Labs/scribble-stadium-fe pull request #120
Opened 2021-06-08 02:26 UTC by silvodesigns

# Pull Request Template

## Added a new folder that contains the audio files for the backEnd
-The motivation for this change is that I decided to host the relative path to audio files in backEnd instead of hosting the audio itself in the database
-You can find the file under src/assets/audio files

2021-06-08 02:48 UTC, Antashma requested changes
Hey the audio folder looks fine.  Just make sure you add that env.sample file back (the one without any sensitive info) and then the tests should pass.

2021-06-08 03:19 UTC, sunkist5691 approved these changes, later dismissed

2021-06-08 18:06 UTC, Antashma approved these changes

2021-06-10 02:00 UTC, kavya3v approved these changes
adding the audio file to the assets in fe looks good.

2021-06-18 01:37 UTC, merged