DisableNotifications button added in NotificationTexDiv of NotificationBotPolygon
BloomTech-Labs/scribble-stadium-fe pull request #141
Opened 2021-08-03 00:57 UTC by askaborg

- Headsup display on top of each screen as you make your way through the app
What this will show:
- What you are working on > what is next > Track progress
- When the user logs in, this would pop-up and then disappear 

---
Add a summary that address the following:
 - motivation/purpose for the feature 
     To give expert users the ability to disable and not be bothered by notifications.
 - What were those changes
     A disable notifications button was added beside the close button of the NotificationBotPolyon.js. 
 - What issues were fixed
     Disable notifications allows the user to focus.
 - Provide the link to the user story it is referencing in Trello board or other supporting document
     https://trello.com/c/elTDaDii/21-as-a-user-i-want-to-change-notification-settings-so-that-i-can-mute-all-notifications

2021-08-10 18:31 UTC, Jtamedrano commented
Something wasn't passing here. can we see what it is before pushing?

2021-08-11 00:10 UTC, tinomen commented
Feel free to remove the template questions.

2021-08-11 00:11 UTC, tinomen commented
In the future let snot commit empty files. It's not at all clear why it's there and the commit will have not value on your activity.

2021-08-11 00:17 UTC, tinomen requested changes
This PR is empty. None of the changes described are present.

2021-08-11 00:17 UTC, tinomen commented on temp.txt
> +This file will log notes for commits and removed when the feature is complete.
Lets not do this in the future. It looks like you are trying to game the github activity graph. But it's really adding noise to the team members who have to review this.

2021-08-11 00:20 UTC, tinomen commented
Closing because there is nothing here.

2021-08-11 00:20 UTC, closed without merging