Feature/heads up display dev
BloomTech-Labs/scribble-stadium-fe pull request #163
Opened 2021-09-02 01:49 UTC by Bmmaroni

# Pull Request Template

Go from a screen that selects the game play of single player or multiplayer. 
When the single player mode is selected it goes into the screen which gives the option to read, write, and/or draw. 
    1. You will be able to check or uncheck draw or write but cannot choose both write and draw together
    2. After chooseing you will be able to upload the drawing or writing to the platform. 
When it is submited a function will pit the player against a randomly chosen boss. 
## Description
Add a summary that address the following:
 - motivation/purpose for the feature 
     To make a gamemode menu for single player where they can choose read write or draw and then upload their writing or drawing
 - What were those changes
     A gamemode menu for uploading a drawing by choosing the button. 
 - What issues were fixed
     A gamemode styled menu
 - Provide the link to the user story it is referencing in Trello board or other supporting document
     https://trello.com/c/Q4Wusyn7/53-create-button-to-select-single-player-mode

## Commits Checklist
- [ ] commits have clear title names 
- [ ] commit has descriptive message of what has changed 
- [ ] more small commits than less big commits 

## Code Checklist 
- [ ] code is formatted appropriately 
- [ ] code meets DRY standards
- [ ] no dead code (check for logs and print statements)  
- [ ] no TODOS instead necessary comments 
- [ ] code follows Story Squad standards for:
     - Language 
     - Framework 
     - Libraries   

### PRs needs to be reviewed by at least 2 team members
 - TPL is the 3rd reviewer 
 - Lots of comments and suggestions, please! 

[Pull Request Rubric](https://www.notion.so/1fc04e4fedeb429ba873b7c68d281707?v=74054da7991341c0bf970f39410c43da)

2021-09-02 01:53 UTC, Bmmaroni commented
![](https://github.trello.services/images/mini-trello-icon.png) [CSS/Animation dates for Progress bar](https://trello.com/c/CJeeiunL/80-css-animation-dates-for-progress-bar)

2021-09-02 01:53 UTC, Bmmaroni commented
![](https://github.trello.services/images/mini-trello-icon.png) [Update state on checker in progress bar](https://trello.com/c/QFP9dzJk/82-update-state-on-checker-in-progress-bar)

2021-09-02 01:53 UTC, Bmmaroni commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add button and collapse](https://trello.com/c/oSjpUO2b/81-add-button-and-collapse)

2021-09-09 21:33 UTC, kwnie requested changes
Good work!

2021-09-09 21:33 UTC, kwnie commented on src/components/pages/HeadsUpDisplay/CountdownTimer.js
> +    console.log(today);
Can we remove this console.log?

2021-09-09 21:33 UTC, kwnie commented on src/components/pages/HeadsUpDisplay/CountdownTimer.js
> +      </div> */}
Do we need this commented out code?

2021-09-09 21:33 UTC, kwnie commented on src/styles/less/Hud.less
> +
We can delete this extra space

2021-09-09 23:41 UTC, Bmmaroni commented on src/components/pages/HeadsUpDisplay/CountdownTimer.js
> +    console.log(today);
Absolutely! Good Catch thank you.

2021-09-09 23:42 UTC, Bmmaroni commented on src/components/pages/HeadsUpDisplay/CountdownTimer.js
> +      </div> */}
Commented code will be removed yes

2021-09-09 23:42 UTC, Bmmaroni commented on src/styles/less/Hud.less
> +
Extra space is outta here!

2021-09-12 17:57 UTC, kdneldor approved these changes, later dismissed
Looks good Brandon! I like the atomic commits. I would imagine that this is mergeable once the requested changes are made / conversations are resolved. Well done.

2021-09-15 01:29 UTC, PLisak777 commented
This all looks good to me, only suggestions I have would be removing a few unused declarations on your Hud.js file.
Line 1: useState is declared but never used
Line 3: Hud import is declared but never used.
Are you maybe saving these for later?

2021-09-16 23:52 UTC, jproctor-rebecca approved these changes
Thank you for resolving the merge conflicts and responding to the change requests so quickly.

2021-09-17 00:07 UTC, TonySo88 approved these changes
Looks great Noel! It was a pleasure working with you on this project.

2021-09-17 00:07 UTC, kwnie approved these changes
Great work! I like the comments, they clarify what is happening with the code.

2021-09-17 00:13 UTC, kdneldor approved these changes
Great work Brandon and team! I like the atomic commits. This looked like a lot of work.

2021-09-17 00:31 UTC, merged

2021-09-17 04:10 UTC, bcanty92 reviewed
Great work team! looks clean .It was a pleasure working with  everyone