changed the name on the parent dashboard from 'story squad' to 'scrib…
BloomTech-Labs/scribble-stadium-fe pull request #180
Opened 2021-10-01 02:05 UTC by Mitch98k

2021-10-08 02:10 UTC, artofmayhem reviewed
on the test file check the lowercase scribble stadium. Should match the header text Scribble Stadium otherwise everything checks out and looks good. Nice to see the new name in action.

2021-10-08 02:11 UTC, venegasgabby76 submitted a review, later dismissed
great job going though the app and replacing the name of the app to the appropriate one.

2021-10-08 23:20 UTC, OniWarrior submitted a review, later dismissed
I've checked all the commits and there's no changes that I can see that would cause breaking changes. The only changes that were performed was the instance change from Story Squad to Scribble Stadium throughout the files that I checked in his commits. Everything is consistent with the exception of one commit in which the font family was changed in the gamemodestyles .less file from atma to bangers. I'm making the assumption this is just an aesthetic change to make the font look a little nicer. Other than that everything looks good and is ready to be merged.

2021-10-10 17:06 UTC, ashtilawat reviewed
Can you rebase main and push this branch up again. We changed gamification to gameplay everywhere in the app. If you rebase, it should fix the merge conflicts.

2021-10-12 15:42 UTC, ashtilawat requested changes
Can you rebase main before I merge this

2021-10-14 04:00 UTC, ashtilawat submitted a review, later dismissed

2021-10-14 22:48 UTC, just-kato submitted a review, later dismissed

2021-10-14 22:48 UTC, just-kato commented on src/components/common/ParentNavTopBar.js
> +          Scribble Stadium
Good job with the name change

2021-10-14 22:48 UTC, just-kato commented on src/components/common/Header.js
> +      <h1 className="header-text">{props.title || 'Scribble Stadium'}</h1>
Good Job

2021-10-14 22:48 UTC, just-kato commented on src/__tests__/Header.test.js
> +    const head = getByText(/scribble stadium/i);
Good job

2021-10-14 22:48 UTC, just-kato commented on src/components/pages/GamePlay/GamePlayMain.js
> +      title: 'Welcome to Scribble Stadium!',
Nice!

2021-10-14 22:48 UTC, just-kato commented on src/styles/less/GamemodeStyles.less
> +        font-family: 'bangers';
Nice font change

2021-10-14 22:48 UTC, just-kato commented on src/utils/helpers.js
> +    'Welcome to Scribble Stadium! To begin your journey click the "READ" icon to start the story! Are you ready to accept the challenge?',
Nice!

2021-10-15 02:40 UTC, bipin-shrestha commented
Thanks Mitchell for taking the time to make the change throughout the app.

2021-10-26 18:13 UTC, casey-dietz submitted a review, later dismissed
Looks great, nice updates! Great video going through all the changes and explaining what work was done. Nice work!

2021-10-28 01:29 UTC, just-kato approved these changes

2021-10-28 01:29 UTC, just-kato commented on src/__tests__/Header.test.js
> +    const head = getByText(/scribble stadium/i);
Nice name change!

2021-10-28 01:29 UTC, just-kato commented on src/components/pages/GamePlay/GamePlayMain.js
> +      title: 'Welcome to Scribble Stadium!',
Looks good

2021-10-28 01:29 UTC, just-kato commented on src/styles/less/GamemodeStyles.less
> +        font-family: 'bangers';
Nice font change

2021-10-28 01:29 UTC, just-kato commented on src/utils/helpers.js
> +    'Welcome to Scribble Stadium. Accept your mission to start an adventure!',
Little changes that matter! Great Job

2021-10-28 01:29 UTC, just-kato commented on src/utils/helpers.js
> +    "Below you will see some graphs representing what we at Scribble Stadium call our 'Squad Score'. What exactly is a Squad Score? We're glad you asked!",
Great job

2021-10-31 00:46 UTC, OniWarrior approved these changes

2021-10-31 05:13 UTC, merged