Syntax cleanup
BloomTech-Labs/scribble-stadium-fe pull request #184
Opened 2021-10-08 20:44 UTC by ethankarp

I changed all instances of "!=" to "!==" and "==" to "===" to clear up the warnings in the terminal.
Trello cards: [A](https://trello.com/c/Y9d9g56f/611-syntax-error-a), [B](https://trello.com/c/cPj2QAGz/612-syntax-error-b)

2021-10-08 21:25 UTC, ghost approved these changes
Nice cleanup!

Also, I like the change from "gamification" to "gameplay" since there seems to be less chance of future spelling errors and "gameplay" seems to be a better description of what's going on.

2021-10-09 00:31 UTC, rhiannonstanford requested changes
Great work overall and good attention to detail!  Just had a few questions on the code.  Thank you.

2021-10-09 00:31 UTC, rhiannonstanford commented on src/index.js
> +import { GamePlayMain } from './components/pages/GamePlay/index';
Just wanted to confirm that the /index is needed on Line 56.  Why was this added? Thank you.

2021-10-09 00:31 UTC, rhiannonstanford commented on .vscode/settings.json
> +  ]
Great work overall.  Why were Lines 3 - 9 added?

2021-10-09 00:49 UTC, artofmayhem commented on .vscode/settings.json
> +  ]
those were from my pr yesterday. They are in the linter so that vscode doesn't highlight our verbiage as misspells

2021-10-09 00:49 UTC, artofmayhem commented on src/index.js
> +import { GamePlayMain } from './components/pages/GamePlay/index';
those are from the changes in his local repo from the changes i made yesterday.

2021-10-09 00:50 UTC, ethankarp commented on src/index.js
> +import { GamePlayMain } from './components/pages/GamePlay/index';
Right, this is from Tony's PR. His PR got merged while my PR was up, so I needed to rebase mine.
It doesn't seem consistent with the rest of the imports, so I'll remove it.

2021-10-09 00:54 UTC, ethankarp commented on src/index.js
> +import { GamePlayMain } from './components/pages/GamePlay/index';
Actually, it does point to a file, so I guess we should leave it.

2021-10-09 01:02 UTC, rhiannonstanford commented on src/index.js
> +import { GamePlayMain } from './components/pages/GamePlay/index';
Excellent! Thank you for checking.  Nice work you two.

2021-10-09 01:02 UTC, rhiannonstanford commented on .vscode/settings.json
> +  ]
Thank you for clarifying.  Excellent work Tony.  Very efficient!

2021-10-09 01:06 UTC, rhiannonstanford approved these changes
Great attention to detail and this clean up will add to the overall MVP! Nice work! Thank you

2021-10-09 01:30 UTC, artofmayhem approved these changes
great job on changing out the syntax issues with the != and == issues. Nice and clean.

2021-10-10 05:11 UTC, merged