Bug/repair game draw step and upload docs warnings
BloomTech-Labs/scribble-stadium-fe pull request #185
Opened 2021-10-08 22:26 UTC by OniWarrior

In the gameDrawStep.js component there were two warnings that needed to be addressed.
 One was a useEffect dependancy warning and the other was a alt text warning on the image element. The useEffect warning was the most important because there was a missing argument in the dependency array on line 100 that was causing performance issues for the application. I added the missing argument of the prop for the file submission drawing and performance has increased significantly. The alt text warning on line 106 was minor in that the text inside the string was redundant in its wording . I made a slight change to the text to repair the warning. 

In the UploadDocs component, there was a missing dependency list for the dependency array on line 121. I added the 3 missing arguments to repair the warning.  The next warning involved improper syntax for a condition on line 117. This was minor; I corrected the syntax and the warning disappeared.

2021-10-08 22:32 UTC, OniWarrior commented
Note: While my changes repaired the warnings and increased performance. There was an unintended side effect. This side effect is minor. The modal window that should appear  when GameReadStep component initially mounts does not appear. I suspect that when the other warnings are repaired that this won't be the case anymore.

2021-10-09 00:59 UTC, ashtilawat requested changes
Looks like the package-lock was committed here. We can't have the package.json or package-lock being committed to the repo. I'm guessing we did a "git add .". Let's only add the necessary files by doing a git add fileName.

2021-10-09 01:14 UTC, OniWarrior commented
Apologies on the package-lock.json file. I deleted the commited file.

2021-10-09 01:58 UTC, ashtilawat23 commented
No need to apologize! We don't want to delete the file from the repo completely. We just want to maintain the version that is on main already. See https://github.com/Lambda-School-Labs/scribble-stadium-fe/pull/186#pullrequestreview-775529017

2021-10-09 02:01 UTC, rhiannonstanford submitted a review, later dismissed
I was able to read through the code changes well and understand the errors you were resolving and how you resolved them through a very descriptive intro to this PR.  Nice work, just need to maintain the package-lock.json file from main.

2021-10-09 02:01 UTC, rhiannonstanford commented on src/components/pages/Gameification/GameDrawStep.js
Nice fix.  This is a better description.

2021-10-09 02:01 UTC, rhiannonstanford commented on src/components/pages/Gameification/GameDrawStep.js
> +  }, [props.fileSubmissionData.drawings]);
This resolves: **./src/components/pages/Gameification/GameDrawStep.js**
Line 100:6:   React Hook useEffect has a missing dependency: 'props.fileSubmissionData.drawings'

2021-10-09 02:01 UTC, rhiannonstanford commented on src/components/common/UploadDocs.js
> +  }, [fileList, filePreviews, savedFileList]);
This line resolves: **./src/components/common/UploadDocs.js**
Line 113:3:   React Hook useEffect contains a call to 'setFilePreviews'

2021-10-09 02:10 UTC, OniWarrior commented on src/components/pages/Gameification/GameDrawStep.js
Thank you.

2021-10-09 02:12 UTC, OniWarrior commented
Ok I followed the instructions in the review and restored the package-lock.json file to what is in main.

2021-10-09 02:13 UTC, ethankarp requested changes
Nice job with these fixes! It looks like you'll need to rebase this in order to merge it. As a reminder, that's a "git pull" on the main branch, then a "git rebase main" on this branch.

2021-10-09 02:13 UTC, OniWarrior commented
I didn't commit and push the file because I didn't want to make the same mistake twice.

2021-10-09 02:18 UTC, OniWarrior commented
Ok I did a git pull on main and a git rebase main on the bug branch. Everything should be ready now.

2021-10-09 02:21 UTC, ethankarp commented
Now if you commit and push, this will be merge-able

2021-10-09 04:23 UTC, OniWarrior commented
The push wasn't successful.  The previous package-lock.json file on the remote branch was interfering with the restored main version. I've tried resolving the issue by following the instructions provided but it's not going through. I've created a brand new clean branch that I'm marking as redo at the end of the branch name. This is the only thing I can think of to resolve this issue.

2021-10-09 10:14 UTC, closed without merging