Feature/win loss tracker
BloomTech-Labs/scribble-stadium-fe pull request #194
Opened 2021-10-10 02:28 UTC by PLisak777

# Pull Request Template

Added a simple increment function to the childReducer.js file that will increment the Childs' win count by 1. Added the corresponding action in childActions.js file. 
This will also serve as a simple increment function that can be used and deployed across the project anywhere we need a simple counter. 

## Description

Add a summary that address the following:

- motivation/purpose for the feature
  To increment a Child's win count by one.
- What were those changes
  Created simple increment reducer function/action to increment Child's win count by 1
- What issues were fixed
  Could not increment Child's win count by 1. Can now Increment Child's win count by 1. 
- Provide the link to the user story it is referencing in Trello board or other supporting document
  https://trello.com/c/bfryS6cr

## Commits Checklist

- [x ] commits have clear title names
- [x ] commit has descriptive message of what has changed
- [ ] more small commits than less big commits

## Code Checklist

- [x ] code is formatted appropriately
- [x] code meets DRY standards
- [x ] no dead code (check for logs and print statements)
- [x ] no TODOS instead necessary comments
- [x ] code follows Story Squad standards for:
  - Language
  - Framework
  - Libraries

### PRs needs to be reviewed by at least 2 team members

- TPL is the 3rd reviewer
- Lots of comments and suggestions, please!

[Pull Request Rubric](https://www.notion.so/1fc04e4fedeb429ba873b7c68d281707?v=74054da7991341c0bf970f39410c43da)
https://www.loom.com/share/86fe0ea8ba0349cbb0ea2ddee324e7b8

2021-10-10 23:05 UTC, achaselittlefield approved these changes
The code is concise, readable and dry. The commits are clear and easy to understand. The loom video also provided any additional information that I may need. Overall good job on the implementation of this feature.

2021-10-11 21:30 UTC, Kyleswillard requested changes
Overall pretty good take a look at the comments and please fix those issues.

2021-10-11 21:30 UTC, Kyleswillard commented on src/components/common/UploadFile.js
> +        <h3></h3>
Why are these headers empty?

2021-10-11 21:30 UTC, Kyleswillard commented on src/components/pages/AudioBook/AddAudiobookModal.js
> +// import { UploadOutlined } from '@ant-design/icons';
Please remove unused imports.

2021-10-11 21:30 UTC, Kyleswillard commented on src/components/pages/AudioBook/AddAudiobookModal.js
> +        * modal will close on completion
Please remove todo text, please migrate todo's to Trello cards so that it is more visible for future use.

2021-10-11 21:30 UTC, Kyleswillard commented on src/components/pages/AudioBook/AddAudiobookModal.js
> +  // };
Please remove commented out code

2021-10-11 21:30 UTC, Kyleswillard commented on src/components/pages/AudioBook/AddAudiobookModal.js
> +        {/* <p>{modalContent}</p> */}{' '}
Please remove commented out code

2021-10-11 21:30 UTC, Kyleswillard commented on package-lock.json
>        "resolved": "https://registry.npmjs.org/stringify-object/-/stringify-object-3.3.0.tgz",
Was this a fresh pull of the repo and install?

2021-10-11 22:00 UTC, tinomen commented
Please rename the header of the description or remove the template text.

2021-10-12 01:48 UTC, PLisak777 commented
Closing PR. 

Initially only meant to include the very last commit. 
Accidentally included a bunch of incomplete commits. 
Closing PR to rebase and submit the correct commit only.

2021-10-12 01:48 UTC, closed without merging

2021-10-12 01:48 UTC, casey-dietz approved these changes
Great job Phil, your code is clean and concise