Href attribute required
BloomTech-Labs/scribble-stadium-fe pull request #196
Opened 2021-10-10 03:28 UTC by kendra4227

Added the correct href link to the parent dashboard.

./src/components/common/ParentNavTopBar.js
Line 66:11: The href attribute is required for an anchor to be keyboard accessible

2021-10-10 21:23 UTC, Yonathan-Admasu728 reviewed
great changes all around. I am a little confused about the local host being hard coded to 3000.  can you explain please!

2021-10-10 22:16 UTC, OniWarrior requested changes
Hello. This is probably going to work but you can't hard code the localhost into the href attribute. Any type of hard coding is considered bad practice.
Instead input this into href.       href = "/parent/dashboard". Test this out, and if it works, recommit.

2021-10-10 22:20 UTC, OniWarrior commented on src/components/common/ParentNavTopBar.js
> +            href="http://localhost:3000/parent/dashboard#"
Put this in the href       "/parent/dashboard ".

2021-10-10 22:27 UTC, OniWarrior commented on src/components/pages/AdminDashboard/DevToolsNew.js
> +        <a
For the anchor elements in this file, these are hard coded with the local host.  We're not allowed to hard code because it's considered bad practice, information is directly exposed. Try this: 

 <   a onClick={handleSatMon}>
  Saturday - Monday
 <  /a>

2021-10-10 22:30 UTC, OniWarrior commented on src/components/pages/AdminDashboard/DevToolsNew.js
> -        <a target="_blank" onClick={handleTues}>
For this one, try this:
< a onClick={handleTues}>
 Tuesday
< /a>

2021-10-10 22:32 UTC, OniWarrior commented on src/components/pages/AdminDashboard/DevToolsNew.js
> -        <a target="_blank" onClick={handleWed}>
For this one, try this: 
<  a  onClick={handleWed}>
  Wednesday
< /a>

2021-10-10 22:32 UTC, OniWarrior commented on src/components/pages/AdminDashboard/DevToolsNew.js
> -        <a target="_blank" onClick={handleThurs}>
For this one, try this:
< a onClick={handleThurs}>
 Thursday
< /a>

2021-10-10 22:33 UTC, OniWarrior commented on src/components/pages/AdminDashboard/DevToolsNew.js
> -        <a target="_blank" onClick={handleFri}>
For this one, try this:
< a onClick={handleFri}>
 Friday
< /a>

2021-10-10 22:39 UTC, OniWarrior commented
I took a look at the handlers in the devToolsNew component. The handlers have already taken care of the redirects that are needed. All that has to be done is insert each handle function to its respective anchor in the onClick attribute. I added comments to show where this can be done.

2021-10-11 17:27 UTC, just-kato requested changes
Good idea in trying to get rid of the error by adding and href tag. However, hardcoding localhost server ports are not the best practice. All I would do is just implement the Href tag with just the routes. Once that is complete this code with be ready to go.

2021-10-11 17:27 UTC, just-kato commented on src/components/common/ParentNavTopBar.js
> +            href="http://localhost:3000/parent/dashboard#"
Interesting. Yes the localhost server port is not supposed to be hard coded. Showing the route is fine

2021-10-11 17:27 UTC, just-kato commented on src/components/pages/AdminDashboard/DevToolsNew.js
> -        <a target="_blank" onClick={handleTues}>
Same error results. Href needs to be present. The error is resolved once if with just adding the route:
`<a
          href="/dev/day/1-3"
          target="_blank"
          rel="noopener noreferrer"
          onClick={handleSatMon}
        >
          Saturday - Monday
        </a>`

2021-10-11 17:27 UTC, just-kato commented on src/components/pages/AdminDashboard/DevToolsNew.js
> -        <a target="_blank" onClick={handleWed}>
Same error results. Href needs to be present. The error is resolved once if with just adding the route:
`a
          href="/dev/day/4"
          target="_blank"
          rel="noopener noreferrer"
          onClick={handleTues}
        >
          Tuesday
        </a>`

2021-10-11 17:27 UTC, just-kato commented on src/components/pages/AdminDashboard/DevToolsNew.js
> -        <a target="_blank" onClick={handleThurs}>
Same error results. Href needs to be present. The error is resolved once if with just adding the route:

` <a
          href="/dev/day/6"
          target="_blank"
          rel="noopener noreferrer"
          onClick={handleThurs}
        >
          Thursday
        </a>`

2021-10-11 17:27 UTC, just-kato commented on src/components/pages/AdminDashboard/DevToolsNew.js
> -        <a target="_blank" onClick={handleFri}>
Same error results. Href needs to be present. The error is resolved once if with just adding the route:


`<a
          href="/dev/day/7"
          target="_blank"
          rel=" noopener noreferrer"
          onClick={handleFri}
        >
          Friday
        </a>`

2021-10-11 17:27 UTC, just-kato commented on src/components/pages/AdminDashboard/DevToolsNew.js
> +        <a
Same error results. Href needs to be present. The error is resolved once if with just adding the route:
`<a
          href="/dev/day/1-3"
          target="_blank"
          rel="noopener noreferrer"
          onClick={handleSatMon}
        >
          Saturday - Monday
        </a>`

2021-10-11 17:27 UTC, just-kato commented on src/components/common/ParentNavTopBar.js
> +            href="/parent/dashboard#"
Href should never hard code localhost server ports "localhost:3000/parent/dashboard/#". Updated the code in removing the server port and keeping the route

2021-10-11 23:01 UTC, kendra4227 commented on src/components/common/ParentNavTopBar.js
> +            href="/parent/dashboard#"
Got it !

2021-10-11 23:26 UTC, kendra4227 reviewed
I understand now, thank you.

2021-10-12 19:53 UTC, closed without merging