Bug - removed declared variables/state that were not being used
BloomTech-Labs/scribble-stadium-fe pull request #202
Opened 2021-10-12 00:17 UTC by ruthmatieu

removed declared variables/state that were not being used

2021-10-12 00:41 UTC, kendra4227 reviewed
When we declare a state variable with useState , it returns a pair — an array with two items. The first item is the current value, and the second is a function that updates it. You only have one variable. I believe you must declare the 'visible' variable somehow.

2021-10-12 02:52 UTC, Alisa1989 submitted a review, later dismissed

2021-10-12 02:52 UTC, Alisa1989 commented on src/components/pages/Gallery/WeeklySubmissions.js
> -  const { user, isAuthenticated } = useAuth0();
why did you delete this line?

2021-10-13 00:56 UTC, just-kato requested changes
Great Job! Please look over the comments and make necessary changes.

2021-10-13 00:56 UTC, just-kato commented on src/components/pages/AccountSettingsForm/ChangePasswordModal.js
> +  const [setVisible] = useState(false);
In this case this would definitely get rid of the error. However, I believe this is bad practice getting rid of the state like this. Try implement this code in a different way. Try props.setVisible(false), wherever you need to implement the "setVisible" state

2021-10-13 00:56 UTC, just-kato commented on src/components/pages/AccountSettingsForm/ChangePasswordModal.js
> +  const [setVisible] = useState(false);
Further. Remove this line of code and implement the setVisible in the way that I mentioned above.

2021-10-13 00:56 UTC, just-kato commented on src/components/pages/Gamemode/GamemodeButton.js
> -  const { push, location } = useHistory();
great job in getting rid of this.

2021-10-13 00:56 UTC, just-kato commented on src/components/pages/Gallery/WeeklySubmissions.js
> -  const { user, isAuthenticated } = useAuth0();
Looks like they were trying to implement some type of authorization and I am unsure if they still need this implemented or not. I'd say just comment the code out instead of deleting it.

2021-11-06 00:59 UTC, Qirhi commented
This student has left. So we will close this PR as it is unresolved.

2021-11-06 00:59 UTC, closed without merging