Bug Fix: Missing return statement in arrow functions
BloomTech-Labs/scribble-stadium-fe pull request #220
Opened 2021-10-13 23:23 UTC by ethankarp

There were two arrow functions that used the "map" array method when "filter" was more appropriate. This lead to there being no return statement for anything that didn't fit the conditional, which created two respective warnings in the console.

Here is the [trello card](https://trello.com/c/4Y1pqTao/616-other-warnings-and-error-c) related to these warnings.

2021-10-14 02:39 UTC, achaselittlefield reviewed
Good job on updating this code and formatting the filter statement to fit on one line. This makes the code more readable and concise. The only other comment I have is making your commit a little more detailed regarding what is being updated. Also adding a loom video would help eliminate any confusion another developer might have regarding this pull request.

2021-10-14 02:48 UTC, rhiannonstanford requested changes
Excellent work, please see comments.

2021-10-14 02:48 UTC, rhiannonstanford commented on src/components/pages/AccountSettings/RenderAccountSettings.js
> +      res.filter(user => setUserInfo(user) && user.type === 'Parent');
Are there any side effects to your code revision?  You are using a fantastic boolean expression to evaluate 1) setUserInfo(user) which will return a boolean and 2) does the user have a type of Parent.  The original code only sets user info if the user object has a parent type.  Your code revision sets user info to every user object.  Since the boolean expression evaluates left to right, I think you can resolve this by switching the order of your statement on Line 19 to:  res.filter(user.type === 'Parent' && user => setUserInfo(user));  In this way, if user doesn't have a parent type, the boolean expression will bail out before ever reaching the state setter.

2021-10-14 02:48 UTC, rhiannonstanford commented on src/state/reducers/parentReducer.js
> +        ),
Nice use of .filter here and boolean expressions.

2021-10-14 20:48 UTC, ethankarp commented on src/components/pages/AccountSettings/RenderAccountSettings.js
> +      res.filter(user => setUserInfo(user) && user.type === 'Parent');
Your worry is completely valid, however, because of the && operator, setUserInfo will only run if the conditional is met. Something to note is that with this exact same syntax, the map method will return boolean values instead of executing the setUserInfo function. That's because the && operator makes the whole thing a boolean expression as you've recognized. The filter method treats it a bit different in that it will return what we first set it to (the setUserInfo function) only if the boolean expression evaluates to true. Since setUserInfo is truthy, this filter method will return the setUserInfo function when the conditional after also evaluates to true.

2021-10-14 23:37 UTC, chrislauyc commented on src/components/pages/AccountSettings/RenderAccountSettings.js
> +      res.filter(user => setUserInfo(user) && user.type === 'Parent');
If you are not returning anything, you don't have to use filter. Instead, just use forEach.

If the line of code is causing confusion, might be good to refactor it. It might be more clear to use a ternary expression instead. Like this: user.type === 'Parent'? setUserInfo(user): ""

Or can just use a good old if statement

2021-10-15 00:57 UTC, Ksouffle commented
After discussion with Jake Mallory, we learned that there were indeed side effect possibilities in the RenderAccountSettings file. This is because of the setUserInfo call before the conditional is checked.

We also learned that an array method is not reasonable there because we didn't want to return an array. The intention is to call setUserInfo with the parent user passed in. I've fixed this by finding the parent user with the "find" method as Jake suggested, and then calling setUserInfo(parent) if a parent was found.

2021-10-15 01:16 UTC, OniWarrior approved these changes
I'm glad we sat in during the meeting with Jake. I think it was really educational for all of us. Good job on the changes.

2021-10-15 01:16 UTC, OniWarrior commented on src/components/pages/AccountSettings/RenderAccountSettings.js
>      });
Awesome.  This is something I was confused on as well. At least now we understand what the proper usage is for map and filter.

2021-10-15 01:16 UTC, OniWarrior commented on src/state/reducers/parentReducer.js
> +        ),
Great job with this filter. This should be more efficient than map because it's filtering and returning an array based upon the condition.

2021-10-15 02:13 UTC, rhiannonstanford approved these changes
Fantastic job and dialogue about your changes.  Thank you!

2021-10-15 05:26 UTC, artofmayhem approved these changes
Nice job digging deep into the how and why of this. I've been following the back and forth on this one and I'm glad to see that we came to a meaningful solution that will be more performant than if we had not taken such time to ensure the code quality. Excellent job

2021-10-15 15:26 UTC, merged