adjusted font size and alignment
BloomTech-Labs/scribble-stadium-fe pull request #228
Opened 2021-10-16 02:17 UTC by bipin-shrestha

# Pull Request Template

Go from a screen that selects the game play of single player or multiplayer.
When the single player mode is selected it goes into the screen which gives the option to read, write, and/or draw. 1. You will be able to check or uncheck draw or write but cannot choose both write and draw together 2. After chooseing you will be able to upload the drawing or writing to the platform.
When it is submited a function will pit the player against a randomly chosen boss.

## Description

Add a summary that address the following:

- motivation/purpose for the feature
  To make a gamemode menu for single player where they can choose read write or draw and then upload their writing or drawing
- What were those changes
  A gamemode menu for uploading a drawing by choosing the button.
- What issues were fixed
  A gamemode styled menu
- Provide the link to the user story it is referencing in Trello board or other supporting document
  https://trello.com/c/Q4Wusyn7/53-create-button-to-select-single-player-mode

## Commits Checklist

- [ ] commits have clear title names
- [ ] commit has descriptive message of what has changed
- [ ] more small commits than less big commits

## Code Checklist

- [ ] code is formatted appropriately
- [ ] code meets DRY standards
- [ ] no dead code (check for logs and print statements)
- [ ] no TODOS instead necessary comments
- [ ] code follows Story Squad standards for:
  - Language
  - Framework
  - Libraries

### PRs needs to be reviewed by at least 2 team members

- TPL is the 3rd reviewer
- Lots of comments and suggestions, please!

[Pull Request Rubric](https://www.notion.so/1fc04e4fedeb429ba873b7c68d281707?v=74054da7991341c0bf970f39410c43da)

2021-10-19 01:09 UTC, milklot submitted a review, later dismissed
Good job, keep the same styling of font will structure more pleasant view.

2021-10-19 01:50 UTC, tinomen requested changes
Just a quick fix on that `.env.sample` file

2021-10-19 01:50 UTC, tinomen commented on .gitignore
> +.env.sample
Remove this line. The sample is meant to be in the repo for future teammates to get an idea of what env vars exist.

2021-11-04 01:47 UTC, PVigar88 approved these changes
Looks good

2021-11-09 02:57 UTC, Julianisrel approved these changes

2021-11-09 02:57 UTC, Julianisrel commented on src/components/pages/WordCountContainer/WordCountContainer.styles.css
> +  width: 525px;
Good style changes, nice and clean.

2021-11-09 04:04 UTC, derekjpeters commented
@bipin-shrestha is this still valid or does this need to be removed?

2021-11-10 02:12 UTC, closed without merging

2021-11-12 04:13 UTC, bipin-shrestha commented
I removed all old pull requests.. cuz I saw others have changed same codes
in thier pull requests.

On Mon, Nov 8, 2021, 8:05 PM derekjpeters ***@***.***> wrote:

> @bipin-shrestha <https://github.com/bipin-shrestha> is this still valid
> or does this need to be removed?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Lambda-School-Labs/scribble-stadium-fe/pull/228#issuecomment-963796833>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQ2JLDHT7VDHVTCQWV4QGPLULCMXNANCNFSM5GDDBORQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>