Feature/changing look of singleplayer button gamemeode component
BloomTech-Labs/scribble-stadium-fe pull request #229
Opened 2021-10-18 02:04 UTC by OniWarrior

In this ticket, I changed the look of the single player component of gamemode component.

Reason for change:
The previous look was basically just a container with a little button at the center which was the link to start single player mode. It didn't look great and it didn't match the look and feel of the other buttons.

Changes made:
I changed the thickness of the border around the container. I made it thinner so it wasn't as pronounced.

I added an animation to slightly scale the container when hovering over it with the cursor. I got rid of the function call that called a function named trig that would render a button component when firing. Instead I replaced the call with the text Single Player. Increased the width and height of the Link component to cover the entire container so that no matter where you clicked in the container it would route you to the next appropriate component.

I added a class name to the container of the link so that in the future when we add more buttons for different gameplay modes we can easily target them with css.

I added coloring, font size and font family to match the styling of the text of the other gameplay buttons in gameplaymain component. I then added some padding to the padding-top property so that the text within the button was pushed down slightly.

Note: when traversing the code base, I tested the GamemodeButton component. I'm 100 percent sure that this is an outdated component that is no longer being used. I believe that this component and the path to this component should be deleted. I didn't do it because that's not what the purpose of this branch was. My submission video has a more visual and detailed explanation to justify my case.

Trello Card: https://trello.com/c/MBKHEPCK/642-import-gameplaymain-from-components-pages-gameplay-index

PR submission video: https://drive.google.com/file/d/1CYO6wsE-7Sz5_kv6UGBYP0vD63gN8c5r/view?usp=sharing

2021-10-18 02:05 UTC, OniWarrior commented
Please watch the PR video. It's really important because it concerns the possible deletion of the GamemodeButton component.

2021-10-18 16:21 UTC, MichaelMcFaddenjr requested changes

2021-10-18 16:21 UTC, MichaelMcFaddenjr commented on src/styles/less/ChildDashboard.less
> +  }
The button looks great. Could you align the text to the center (vertically) so it matches the other game play buttons.

2021-10-19 01:05 UTC, milklot approved these changes
Good job on a button styling. Also you can use useHistory hook and put push redirection into  onClick event of the button instead of the links, so styling for buttons and links will be the same.

2021-10-19 01:43 UTC, rhiannonstanford approved these changes
Fantastic job explaining what you have done in this PR.  Great catch on the redundant code as discussed at the end of your PR video.  This has been reviewed and will be addressed in a future PR.  Thank you!

2021-10-19 14:34 UTC, OniWarrior commented
Hey guys I redesigned the single player button. I'm closing this PR because the redesign is big enough to where it would make this PR too big. Michael, the changes that you requested have been made. Just go over to the new PR and test.

2021-10-19 14:34 UTC, closed without merging