increased label text size and submit button darker
BloomTech-Labs/scribble-stadium-fe pull request #230
Opened 2021-10-19 01:53 UTC by kendra4227

I increased the label text size to 18px for better visibility.  I made the submit button darker.
I am currently stuck on ParentContact.less  lines 94-96 , trying to change the color of the submit button when all input fields are filled. Any suggestions would be helpful. 

Reference to Trello Ticket: https://trello.com/c/wbyKwyNm/648-import-parentcontact-from-components-pages-parentcontact

2021-10-19 03:48 UTC, artofmayhem submitted a review, later dismissed
Nice clean up on the extra router imports that were not needed. Good fix on color setting that to standard

2021-10-19 19:10 UTC, mollybee submitted a review, later dismissed
Great job cleaning up the React imports. Changing the background color and font-size looks done correctly.

2021-10-19 22:56 UTC, milklot submitted a review, later dismissed
Text looks more readable and less errors in the console output. Good job!

2021-10-20 00:46 UTC, MichaelMcFaddenjr submitted a review, later dismissed
Nice job. Good clean work!

2021-10-20 00:46 UTC, MichaelMcFaddenjr commented on src/components/pages/Gamemode/Gamemode.js
> +import { Link, Route } from 'react-router-dom';
Good clean up!

2021-10-20 03:01 UTC, OniWarrior submitted a review, later dismissed
Great job with the cleanup on the unused imports and the stylings.

2021-10-20 03:01 UTC, OniWarrior commented on src/components/pages/Gamemode/Gamemode.js
> +import { Link, Route } from 'react-router-dom';
I'm wondering why they brought in BrowserRouter and Switch because don't belong there. They belong in the App function in index.js. This was a good catch.

2021-10-20 03:03 UTC, OniWarrior commented
Just make sure to rebase with main to resolve conflicts or you can click the Resolve conflicts button to change the file directly.

2021-10-20 03:08 UTC, OniWarrior commented
And for changing the color of the submit button after submission.  You could have a boolean value that would change to true after all inputs are filled. Once this happens you could use css to change the color on the condition that the boolean value is true.

2021-10-28 00:11 UTC, Alisa1989 requested changes
the back-ground color is not an approved color:
https://www.figma.com/file/U9Lo9qjZgl4Vbgb2cCMq2v/Story-Squad---Labs?node-id=522%3A1456

2021-10-28 00:13 UTC, Alisa1989 requested changes

2021-10-28 00:13 UTC, Alisa1989 commented on src/styles/less/ParentContact.less
> +  background-color: #535050;
The color you removed is on out palette, the new on eisn't

2021-10-28 00:17 UTC, Alisa1989 commented
> the back-ground color is not an approved color: https://www.figma.com/file/U9Lo9qjZgl4Vbgb2cCMq2v/Story-Squad---Labs?node-id=522%3A1456

2021-10-28 00:17 UTC, closed without merging