Feature/gallery container style
BloomTech-Labs/scribble-stadium-fe pull request #231
Opened 2021-10-19 04:06 UTC by venegasgabby76

### Pull Request Template

**Description**

- adjusted the media queries to be more responsive

**motivation/purpose for the feature**

- make sure that the gallery is responsive.

**What were those changes**

- made appropriate changes to the galleryview.less file

Commits Checklist
[X ] commits have clear title names
[ X] commit has descriptive message of what has changed
[X ] more small commits than less big commits

**Loom Video**

- https://www.loom.com/share/d26810e79a9d4a82af0bba4346f8b2b6

PRs needs to be reviewed by at least 2 team members
TPL is the 3rd reviewer
Lots of comments and suggestions, please!
Pull Request Rubric

2021-10-19 08:19 UTC, chukalicious commented on src/components/pages/Gallery/Weekly.js
> +                // {...pageUrl.map(page => (
If you're not going to use this block it'd be good to delete it

2021-10-19 08:25 UTC, chukalicious submitted a review, later dismissed
Thank you, Gaby! More changes to the data are expected this week, which means the props in these components will need to be further updated but this is a good start!

2021-10-20 00:56 UTC, milklot commented on src/components/pages/Gallery/Weekly.js
> +  console.log(pageUrl);
I will advise comment or delete the console.log after use when you don't need it

2021-10-20 00:58 UTC, milklot submitted a review, later dismissed
Good job on a responsive styling , I will advise comment or delete the console.log after use when you don't need it

2021-10-20 02:14 UTC, ashtilawat requested changes
Let's remove that console.log then and I will merge it ASAP.

2021-10-20 23:45 UTC, ashtilawat approved these changes

2021-10-21 01:17 UTC, ashtilawat approved these changes

2021-10-21 03:27 UTC, chukalicious approved these changes

2021-10-21 06:50 UTC, Aaron-TheCreator approved these changes
We love some good responsive design. Thank you for having clean code, good less fundamentals.

2021-10-21 14:35 UTC, merged