Bug/remove duplicate routes
BloomTech-Labs/scribble-stadium-fe pull request #244
Opened 2021-10-21 00:30 UTC by OniWarrior

In this ticket, I removed a duplicate Protected Route component from src/index.js:

There were two Protected Route components that were meant to render the Parent Dashboard. There was nothing to this I just removed the duplicate. The first Protected Route had the path "/ " and the second had the path "/parent/dashboard". I deleted the second component.

Motivation:
This task was just meant to clean up the routing.

Trello card: https://trello.com/c/ZLfeRrNm/662-parentdashboard-fix-bug-related-to-protectedroutes

PR submission: https://drive.google.com/file/d/1KoSccsp2XspwFpg_8Y_DbKMoelqkkBbq/view?usp=sharing

2021-10-21 00:57 UTC, rhiannonstanford submitted a review, later dismissed
Great job identifying this redundancy and cleaning up the routes!

2021-10-21 03:57 UTC, ghost requested changes
I like that you are cleaning up the routes, but make sure any paths you remove aren't being used throughout the code. I did a quick search and found a few components that were using the path and need to be updated.

![image](https://user-images.githubusercontent.com/69640436/138208929-2950c867-d64d-4938-8b6b-926bc5b34f30.png)

2021-10-21 03:57 UTC, ghost commented on src/index.js
> -          path="/parent/dashboard"
The ParentDashboard, ParentNavSider, and ParentNavTopBar components use the "/parent/dashboard" path. They should be updated if you are removing that path completely from the routes.

2021-10-21 04:18 UTC, venegasgabby76 commented on src/index.js
> -          path="/parent/dashboard"
I agree with Berry!always make sure that any paths that connect are always taken into consideration.

2021-10-21 13:56 UTC, just-kato submitted a review, later dismissed

2021-10-21 13:56 UTC, just-kato commented on src/index.js
> -        <ProtectedRoute
Awesome! Duplicate is gone. Nice work

2021-10-21 13:56 UTC, just-kato commented on src/index.js
> +          exact
Nice work this route should def be on top

2021-10-21 15:15 UTC, MichaelMcFaddenjr commented on src/index.js
> -          path="/parent/dashboard"
Good catch Barry. when deleting things, its also good to do a search to make sure the code is cleaned of any remnants.

2021-10-21 15:15 UTC, MichaelMcFaddenjr requested changes
Make sure to clear this route in any other component.

2021-10-21 15:31 UTC, OniWarrior commented on src/index.js
> -          path="/parent/dashboard"
Apologies on that. I'll do a sweep and get that cleaned up

2021-10-21 19:33 UTC, OniWarrior commented
Ok, changes that were requested have been made. Ready for review.
Note: There may be additional deprecated components that I may have found.

2021-10-21 19:36 UTC, ghost requested changes
Thanks for correcting all the paths. Was removing the FAQ intentional? I know it shows up in the search, but I believe it goes somewhere separate.

2021-10-21 19:36 UTC, ghost commented on src/index.js
> -        />
Why are we removing the FAQ? Is it no longer being used?

2021-10-21 20:24 UTC, OniWarrior commented on src/index.js
> -        />
I checked ParentDashFaq component. Because of what is suppose to be rendered by that component, there's reason to believe that ParentDashFaq is a deprecated component. It has the same format of what is being rendered by the component ParentFaq. This leads me to believe that ParentDashFaq was the previous implementation to ParentFaq.

2021-10-21 20:28 UTC, ghost commented on src/index.js
> -        />
I just checked them both out, and I believe you're right.

2021-10-21 20:28 UTC, ghost approved these changes

2021-10-21 21:01 UTC, MichaelMcFaddenjr approved these changes

2021-10-21 21:01 UTC, MichaelMcFaddenjr commented on src/components/common/ParentNavTopBar.js
>          <Title className="title navbar-logo" level={1}>
good job catching these other route references

2021-10-22 01:03 UTC, milklot approved these changes
There's so much things which are unused and just flows in the App. Thanks for clean up, great job 👍

2021-10-23 04:44 UTC, merged

2021-10-25 19:13 UTC, Julianisrel commented on src/components/common/ParentNavSider.js
> +          <Link to="/">Dashboard</Link>
Good work! placing the correct routes.