add conditional styling for countdown timer position
BloomTech-Labs/scribble-stadium-fe pull request #248
Opened 2021-10-21 02:07 UTC by mollybee

![chrome_LoKKlllP5s](https://user-images.githubusercontent.com/21160325/138200099-ffb91670-9dac-4319-b858-93c574efb37c.png)

![chrome_2SLaL4blHB](https://user-images.githubusercontent.com/21160325/138981902-3bc640ed-eb5b-4d47-b440-b14f2d946f3d.png)

Trello Card: https://trello.com/c/kbPXNecH/518-child-dashboard-adjust-time-remaining-element

2021-10-21 02:08 UTC, mollybee commented on src/components/pages/HeadsUpDisplay/Hud.js
> +function Hud(props) {
Naming the function, and then exporting it, gives it a clear name in the React DevTools for chrome. `export default function` makes it show up as `anonymous`.

2021-10-21 02:09 UTC, mollybee commented on src/components/pages/HeadsUpDisplay/Hud.js
> +  );
I use this to determine if the timer should be in position 1, 2, or 3

2021-10-21 02:10 UTC, mollybee commented on src/components/pages/HeadsUpDisplay/Hud.js
> +        <div className={`ctimer pos-${countdownTimerPositionIndex}`}>
I have three classes `pos-1`, `pos-2`, `pos-3`. Each one centers the timer above one of the three sections called out in the Trello card.

2021-10-21 02:10 UTC, mollybee commented on src/components/pages/HeadsUpDisplay/Hud.js
> +};
I saw `propTypes` used in a couple of other components and thought it would be a nice way to document this component

2021-10-21 02:10 UTC, mollybee commented on src/styles/less/Hud.less
> +}
Here are the three different position classes

2021-10-21 02:11 UTC, mollybee commented on src/styles/less/Hud.less
> -    text-align: center;
I removed this, because it was causing a conflict when I tried to position the element from outside/above the component that used this class.

2021-10-21 06:01 UTC, rhiannonstanford requested changes
Please add code to increase character spacing of time remaining element.  This will complete the Trello.  Thanks!

2021-10-21 06:01 UTC, rhiannonstanford commented on src/styles/less/Hud.less
> +
I didn't see the code related to increasing the character spacing of the time remaining element.  Did I miss it?   https://trello.com/c/kbPXNecH

2021-10-27 01:49 UTC, rhiannonstanford approved these changes
Nice work!  Great job adding that last bit of character spacing.  Thank you!

2021-10-28 00:28 UTC, Alisa1989 approved these changes

2021-10-28 02:08 UTC, merged