added containers for appropriate links margin size, added links styli…
BloomTech-Labs/scribble-stadium-fe pull request #254
Opened 2021-10-22 00:56 UTC by milklot

Bottom Nav Bar: Fix Links FIXED

File path : src/components/pages/GamePlay/Footer.js
Put links in the container for the correct margin purpose.

File path: src/styles/less/GamemodeStyles.less
Changed color of links and added underline styling as on a Trello card.
Added hover effect.

The redirection pages for those link are no exist yet. I left them blank for now. In the App there'r some pages exist , but on a parent side. Not sure if child should have an access/redirection on a parent side of App.

Trello card :
https://trello.com/c/eLbyLM41/660-bottom-nav-bar-fix-links

Let me know if you have any suggestions / recommendations for it, thanks

2021-10-26 02:02 UTC, Veilios submitted a review, later dismissed
Everything looks clean and easy to follow! Nice work!

2021-10-26 03:17 UTC, rhiannonstanford requested changes
Great job!  Please see comments.  Just change to "FAQ"   Thank you!

2021-10-26 03:17 UTC, rhiannonstanford commented on src/components/pages/GamePlay/Footer.js
> +              FaQs
Please change this to "FAQ"

2021-10-26 22:57 UTC, milklot commented on src/components/pages/GamePlay/Footer.js
> +              FaQs
Done

2021-10-27 01:52 UTC, rhiannonstanford approved these changes
Thank you for that change!  Looks great!

2021-10-27 02:02 UTC, mollybee approved these changes
Container naming looks good and descriptive

2021-10-27 02:12 UTC, merged