child progress bar styling
BloomTech-Labs/scribble-stadium-fe pull request #256
Opened 2021-10-26 01:19 UTC by Julianisrel

{ Hud.less: styles changes }

* Corrected left progress bar overlay
* Increased character spacing of titles
* Increased font size of titles
* Corrected title alignment
* Moved minimize arrow down, make it bigger

<img width="1240" alt="Screen Shot 2021-11-08 at 7 40 27 PM" src="https://user-images.githubusercontent.com/61174160/140857934-2d1202da-2a98-449f-9132-0670dc69ca1f.png">

2021-10-26 01:53 UTC, Veilios submitted a review, later dismissed
Clean code! Everything looks great!

2021-10-26 17:51 UTC, ethankarp requested changes
Nice job 👍. I just have a few questions and am asking for a few changes. I noticed you deleted the package-lock.json file. While we don't want to make any changes to it, we need to keep it intact. If you run `git restore origin/main package-lock.json`, you'll get the file back as it is in the main branch. Then just commit it and push it up on this branch.

2021-10-26 17:51 UTC, ethankarp commented on src/styles/less/Hud.less
> +	letter-spacing: .2rem;
This letter-spacing and font-size affect everything because it's in the root selector. I think we'll want to put these in the HudContainer so we only affect the HUD.
Also, I'm curious why you added a 0 before the .75 for --min-height, but didn't do the same for letter-spacing.

2021-10-26 17:51 UTC, ethankarp commented on src/styles/less/Hud.less
> +.HudContainer {progr
Is this "progr" supposed to be here?

2021-10-26 17:51 UTC, ethankarp commented on src/styles/less/Hud.less
> +    // background-color: var(--green);
I see you fixed the overflow by commenting this out and making the whole progressionBar green, however, I think the completed sections are supposed to be green, while the non-completed are supposed to be white. Correct me if I'm wrong on that and if it's been decided to have the whole bar green.

2021-11-09 03:41 UTC, Qirhi commented on src/styles/less/Hud.less
> +.HudContainer {progr
removed

2021-11-09 03:43 UTC, Qirhi approved these changes
Changes made.  Comments resolved.

2021-11-09 03:43 UTC, Qirhi commented on src/styles/less/Hud.less
> +	letter-spacing: .2rem;
Corrected.  Good catch.

2021-11-09 04:30 UTC, Ksouffle approved these changes

2021-11-09 14:00 UTC, merged