Pull request is the first of many for building out this componentFeature/child/winner
BloomTech-Labs/scribble-stadium-fe pull request #258
Opened 2021-10-26 13:55 UTC by zzeroyzz

# Pull Request Template

After the "scores" screen I installed a route that will showcase the winner. I created a "Winner" folder that houses the Winner component. Within that folder I created 3 files: index.js, RenderWinnerPage.js, WinnerPageContainer.js I did not yet add content to these files. I wanted to get the files merged before continuing.

## Trello Card

https://trello.com/c/C0WQBlMt/683-child-winner-route-and-component-creation

## Commits Checklist

- [x ] commits have clear title names
- [x ] commit has descriptive message of what has changed
- [x ] more small commits than less big commits

## Code Checklist

- [x ] create protected route
- [ x] create Winner folder under components/pages/Winner
- [ x] create index.js in Winner folder
- [ x] create RenderWinnerPage.js in Winner folder
- [ x] create WinnerPageContainer.js in Winner folder
- [ x] import Winner component into index.js

2021-10-26 17:21 UTC, artofmayhem requested changes
Did you make a construction page? You can take it right from the one I did on ya play/trophy-room if not. They're all going to be identical so at least something renders saying under construction.

2021-10-26 22:42 UTC, just-kato commented
> Did you make a construction page? You can take it right from the one I did on ya play/trophy-room if not. They're all going to be identical so at least something renders saying under construction.

2021-10-26 23:25 UTC, MichaelMcFaddenjr submitted a review, later dismissed
Nice work.

2021-10-26 23:25 UTC, MichaelMcFaddenjr commented on src/components/pages/WinnerPage/RenderWinnerPage.js
> +          <h1>Winner Page UI Coming Soon!</h1>
Thank you for identifying what the page will be upon completion

2021-11-02 00:36 UTC, Qirhi approved these changes, later dismissed
Nice work filling in the gap for Winner page.  This will aid the route refactor.

2021-11-02 01:35 UTC, artofmayhem submitted a review, later dismissed

2021-11-02 01:44 UTC, Qirhi approved these changes
Looks good with changes from resolved merge conflict.

2021-11-02 01:46 UTC, artofmayhem approved these changes
thank you for resolving merge conflicts @ashtilawat23! Rock star status

2021-11-02 01:46 UTC, merged