Features/fix accept explossive button
BloomTech-Labs/scribble-stadium-fe pull request #263
Opened 2021-10-27 22:34 UTC by Yonathan-Admasu728

This PR  changes the appearance of the Accept mission button:
In this PR I Pair Programed with Tony Miller.  Tony's Role was as a Navigator and mine was as a Driver
./src/components/pages/GamePlay/GamePlayMain.js
line 14: imported the explosion.png from the assets.
line 108 - 110: gave it a classname, gave it alt attribute and used it as img src ="" 
./src/styles/less/Gamemodestyles.less
line 40 - 54: styled it to match the desired specs. using z-index to pop up the button txt with some shadow effect on the explosive-star like background.

Resolves Trello card: https://trello.com/c/eROpAytG/658-gameplay-add-design-vector-to-accept-the-mission-button
PR video walkthrough:https://loom.com/share/d59d4223b60640d7b4055be8f0906cef

2021-10-27 22:42 UTC, rhiannonstanford approved these changes
Wonderful work! Nice job changing the look of the page to match the Figma.  Thank you!

2021-10-27 22:56 UTC, artofmayhem approved these changes
Well done Yonathan! Nice and clean. Fun time pair coding this with you!

2021-10-28 00:25 UTC, Alisa1989 requested changes

2021-10-28 00:25 UTC, Alisa1989 commented on src/styles/less/GamemodeStyles.less
> +        background: #C6FD7E
make sure this color is approved:
https://www.figma.com/file/U9Lo9qjZgl4Vbgb2cCMq2v/Story-Squad---Labs?node-id=522%3A1456

2021-10-28 01:54 UTC, ghost commented on src/styles/less/GamemodeStyles.less
> +        background: #C6FD7E
The color didn't actually change. The hex code is just capitalized now, but it is in the figma color palette.

2021-10-28 10:38 UTC, Yonathan-Admasu728 commented on src/styles/less/GamemodeStyles.less
> +        background: #C6FD7E
these colors are not part of the changes in this PR.  I have mentioned all lines in each files which are part of the change in this PR

2021-10-28 22:42 UTC, Alisa1989 approved these changes

2021-10-29 00:59 UTC, merged