Feature/new password edit form
BloomTech-Labs/scribble-stadium-fe pull request #298
Opened 2021-11-05 01:12 UTC by Alisa1989

The object of this pull request was to create a new form to change the user password.

The initial objective was actually to make the existing settings form functional but it didn't make sense how it was set, as it prompted the user to change the password and email at the same time without actually prompting for a new password.

I consulted my project leader and we came to the conclusion that the settings page would need to be split into two separate pages, one for changing the email, one for changing the password.

In this PR I created and styled the new parent/changepassword page

[trello link](https://trello.com/c/tRqKT6Bi/687-make-edit-parent-settings-functional)

https://user-images.githubusercontent.com/37967343/140441700-4456e9c4-ba45-483c-8e67-c111699c934c.mp4

2021-11-08 04:12 UTC, Fry-Fr commented on src/index.js
> +        />
Should the component be rendered by ProtectedRoute instead? Right now you have Route to render ChangePassword.

2021-11-11 20:18 UTC, artofmayhem submitted a review, later dismissed
Well conceived and executed change.

2021-11-11 23:00 UTC, zzeroyzz submitted a review, later dismissed

2021-11-11 23:00 UTC, just-kato commented on src/components/pages/FamilySettings/ChangePassword.js
> +
I know we talked about you creating this form. It's nice to see it come to life. Great job

2021-11-11 23:00 UTC, just-kato commented on src/index.js
> +import ChangePassword from './components/pages/FamilySettings/ChangePassword';
Nice work

2021-11-11 23:00 UTC, just-kato commented on src/index.js
> +          exact
Great job

2021-11-11 23:00 UTC, zzeroyzz commented on src/styles/less/ChangePassword.less
> +    border-radius: 0px;
Nice work

2021-11-11 23:00 UTC, zzeroyzz commented on src/styles/less/index.less
> +@import 'ChangePassword';
Great job

2021-11-15 03:22 UTC, BryanPAnderson reviewed
good job!

2021-11-15 03:22 UTC, BryanPAnderson commented on src/styles/less/index.less
> +@import 'ChangePassword';
great work

2021-11-16 02:37 UTC, tinomen requested changes
Lets get some of these suggested changes taken care of and merge.

2021-11-16 02:37 UTC, tinomen commented on src/index.js
>          {/* UNDER CONSTRUCTION HOLDER / New path to point to /gameplay/mission/next-steps NOT for DELETE */}
Is this comment needed? If we don't know, then delete it.

2021-12-17 02:56 UTC, Fry-Fr submitted a review, later dismissed
changes appear to be resolved. this works fine.

2021-12-22 23:55 UTC, StnsGeneral submitted a review, later dismissed
Looks much better after the changes.

2022-01-13 05:21 UTC, closed without merging