BugFix for mobile-tablet responsiveness. Trello Card https://trello.c…
BloomTech-Labs/scribble-stadium-fe pull request #317
Opened 2021-11-10 01:47 UTC by PLisak777

…om/c/Vrxo9t1a

# Pull Request Template

In reference to Bug: Responsiveness for Mobile & Tablet is not present trello card https://trello.com/c/Vrxo9t1a
Added reusable React hook to automatically adjust dimensions based on window size. This hook can be called by the UI/UX team in any place they need to use it. 

## Description

Add a summary that address the following:

- motivation/purpose for the feature
  To correct issues with mobile/tablet views and make the UI/UX presentation more responsive
- What were those changes
  Created and exported a reusable React hook windowDimensions.js to be implemented by the UI/UX Team wherever it's necessary
- What issues were fixed
  React hook will automatically adjust dimensions based on the 'resize' event listener whenever the viewport size is changed. 
- Provide the link to the user story it is referencing in Trello board or other supporting document
  https://trello.com/c/Vrxo9t1a

## Commits Checklist

- [x] commits have clear title names
- [x] commit has descriptive message of what has changed
- [x] more small commits than less big commits

## Code Checklist

- [x] code is formatted appropriately
- [x] code meets DRY standards
- [x] no dead code (check for logs and print statements)
- [x] no TODOS instead necessary comments
- [x] code follows Scribble Stadium standards for:
  - Language
  - Framework
  - Libraries

### PRs needs to be reviewed by at least 2 team members

- TPL is the 3rd reviewer
- Lots of comments and suggestions, please!

[Pull Request Rubric](https://www.notion.so/1fc04e4fedeb429ba873b7c68d281707?v=74054da7991341c0bf970f39410c43da)

2021-12-11 16:25 UTC, melanie-mendoza requested changes
Phil, great effort in trying to correct responsiveness issues with mobile and tablet views! Your code looks clean and easy to read. However, my suggestion would be to attach a  brief Loom video in the description going over its purpose and the steps you took to create it. Most importantly, I would include in the video an example of where and how you utilized this code to make a page more responsive.

Lastly, thanks to Ash for requesting me as a reviewer for this PR.

2021-12-14 02:29 UTC, PVigar88 commented on src/utils/windowDimensions.js
> +  const { innerWidth: width, innerHeight: height } = window;
Wow! This is great!  I never would have even thought to do this to make the apge more responsive to dimension changes

2021-12-14 02:29 UTC, PVigar88 approved these changes
Looks Good!  Creative way to solve the responsiveness! I never would have thought of this

2021-12-17 04:57 UTC, melanie-mendoza approved these changes

2021-12-17 18:12 UTC, merged