Bug/back to dashboard button style fix
BloomTech-Labs/scribble-stadium-fe pull request #349
Opened 2021-12-10 04:15 UTC by bipin-shrestha

Fixed the buttons "Go to Point Share" and "back to Dashboard"

2021-12-10 04:26 UTC, PVigar88 commented on src/components/pages/Leaderboard/RenderLeaderboard.js
> +          style={{ margin: '1rem' }}
Should we be coding in-line styles?  seems better suited to be in the sass.

2021-12-10 04:28 UTC, PVigar88 commented on src/components/pages/MatchUp/RenderMatchUp.js
> +          style={{ marginTop: '1rem' }}
similar to above question about in-line styles. I see that the first button had the in-line initially.

2021-12-10 04:28 UTC, PVigar88 requested changes
Code looks good, just had a question about in-line styles being used.

2021-12-10 04:43 UTC, Mitch98k requested changes
Could you insert a link to the trello card for this bug? It would really help to have more context readily available.

2021-12-10 04:43 UTC, Mitch98k commented on src/components/pages/Leaderboard/RenderLeaderboard.js
> +          Back to Dashboard
Nice name change, no reason for the UI to say child or parent dashboard.

2021-12-10 04:43 UTC, Mitch98k commented on src/components/pages/MatchUp/RenderMatchUp.js
> +          className="back-btn"
Good idea giving these buttons a className. If more styling is needed in the future, we can take out the inline style and put it with the class styling.

2021-12-16 04:24 UTC, chrislauyc requested changes
Good work implementing the fix. Please also attach the Trello link and a loom video going over your changes and why you made them.

2021-12-16 21:41 UTC, closed without merging

2021-12-16 21:42 UTC, derekjpeters commented
Closing PR.  There are conflicts that @felipe-sq will be working on.  Bipin has graduated so Felipe will proceed with the changes.