working on draft of get winner
BloomTech-Labs/scribble-stadium-fe pull request #372
Opened 2022-02-01 04:27 UTC by Rachel311

# Description

Fixes #

- What work was done?
- Why was this work done?
- What feature / user story is it for?
- Any relevant links or images / screenshots

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Change Status

- [ ] Complete, tested, ready to review and merge
- [ ] Complete, but not tested (may need new tests)
- [ ] Incomplete/work-in-progress, PR is for discussion/feedback

## Has This Been Tested

- [ ] Yes
- [ ] No
- [ ] Not necessary

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] My code has been reviewed by at least one peer
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] There are no merge conflicts

2022-02-03 04:27 UTC, IsaacGHoward commented
Instead of passing in a squadID of '1', wouldn't you want to take a number based on the squad ID that the child is in?

2022-02-03 04:28 UTC, IsaacGHoward requested changes
I would make it so that you could pass a squadId in instead of defaulting to 1

2022-02-03 19:08 UTC, ashtilawat23 requested changes
Let's take package-lock out of this PR. There seems to be 26K lines of code added to this PR. We want to keep the PR atomic.

2022-02-10 00:20 UTC, rikaciminieri commented on src/components/common/GetWinnerButton.js
> +      .get('http://localhost:5000/api/game/results?squadId=1')
I'm assuming the squad ID is hardcoded for now, just making note of it. Also we should probably be using the apiAuthGet() function to do the axios call to ensure those making the request are authenticated.

2022-02-10 00:22 UTC, rikaciminieri commented
Good work overall! It would be helpful to fill out the description so that we can get an overview on what you worked on before looking at the code. Also, the title of the PR makes it sound like it isn't complete yet, but it seems like you completed the feature in the last commit.

2022-02-23 02:37 UTC, closed without merging