Features/display episode
BloomTech-Labs/scribble-stadium-fe pull request #374
Opened 2022-02-01 04:56 UTC by victoriatrac

# Description

Fixes #

- What work was done? added initial state, utilized axios call and getApiUrl() with refactored components to pull data from state
- Why was this work done? the past content was hardcoded
- What feature / user story is it for? As an evaluator, I want to vote on which top story and picture was the best, so that the game can determine a winner
- Any relevant links or images / screenshots

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Change Status

- [x] Complete, tested, ready to review and merge
- [ ] Complete, but not tested (may need new tests)
- [ ] Incomplete/work-in-progress, PR is for discussion/feedback

## Has This Been Tested

- [ ] Yes
- [ ] No
- [x] Not necessary

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My code has been reviewed by at least one peer
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] There are no merge conflicts

## Pair Programming

- Who you paired with? Kyle Cardwell
- What pairing method(s) you used? Driver and navigator
- How did it go? What did you learn? It went well!

2022-02-03 19:09 UTC, ashtilawat23 requested changes
Can I get a quick loom demoing this? Try to go over your code as well

2022-02-09 03:32 UTC, rikaciminieri commented on src/components/pages/GamePlay/GameReadStep.js
> +    axios
Should the axios call be made in the api index file? Just to keep them all in the same place. A function could be made in the api index file that also calls getApiUrl.

2022-02-10 02:57 UTC, Kishkuman13 approved these changes
Everything looks good, very clean and I like the added comments explaining your code.

2022-02-16 02:20 UTC, ashtilawat23 approved these changes

2022-02-16 02:20 UTC, merged