Bug/delete old admin dashboard
BloomTech-Labs/scribble-stadium-fe pull request #375
Opened 2022-02-08 00:08 UTC by RodolfoJaspe

# Description

Fixes #

- What work was done?
Deleted previous work for Admin Dashboard

- Why was this work done?
A new Admin Dashboard will be created from scratch

- What feature / user story is it for?
https://trello.com/c/PWdISCLn/819-as-an-admin-i-want-a-page-where-i-can-manage-our-site-so-that-i-can-have-a-secure-place-to-manage-the-site

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)

## Change Status

- [ ] Complete, tested, ready to review and merge

## Checklist

- [ ] I have performed a self-review of my own code
- [ ] My code has been reviewed by at least one peer
- [ ] My changes generate no new warnings
- [ ] There are no merge conflicts

https://www.loom.com/share/906a30c7fdc44b15ab70347301d5a202

2022-02-08 00:57 UTC, ragerdude submitted a review, later dismissed
This looks quite nice. Keep up the good work! I don't know FE that well, so you may want to get an extra set of eyes on it who knows this better than I do.

2022-02-10 02:51 UTC, Kishkuman13 requested changes
I believe there is still an import for the DeveloperOperations.less file in the index.less file line 37. Other than that, it looks good.

2022-02-15 02:08 UTC, RodolfoJaspe commented
@Kishkuman13 Got it, thanks! I also deleted that DeveloperOperations.less file since it was part of the work to be replaced

2022-02-15 02:47 UTC, Kishkuman13 approved these changes

2022-02-16 02:20 UTC, ashtilawat23 approved these changes

2022-02-16 02:20 UTC, merged