Feature/audiobook
BloomTech-Labs/scribble-stadium-fe pull request #93
Opened 2021-05-19 02:56 UTC by Claeb1mb

Audiobook boilerplate files & folder created.

2021-05-19 02:59 UTC, Antashma commented
looks good

2021-05-19 03:00 UTC, Antashma approved these changes, later dismissed

2021-05-19 03:03 UTC, kavya3v approved these changes, later dismissed
Approved, please proceed . Note: To clean up import in RenderAudioBook

2021-05-19 03:23 UTC, sunkist5691 requested changes

2021-05-19 03:23 UTC, sunkist5691 commented on src/components/pages/AudioBook/AudioBookContainer.js
> +function AudioBook(...props) {
Try to destructure instead of using only props.

2021-05-19 03:23 UTC, sunkist5691 commented on src/components/pages/AudioBook/AudioBookContainer.js
> +function AudioBook(...props) {
{ LoadingComponent, ...props }

2021-05-20 23:20 UTC, Claeb1mb reviewed
changes made thanks Joon

2021-05-20 23:28 UTC, sunkist5691 approved these changes

2021-05-21 01:59 UTC, kavya3v approved these changes
Destructure looks fine

2021-05-21 03:31 UTC, Antashma approved these changes
👍

2021-05-21 03:58 UTC, merged